version: "3.9"

services:
  backend:
    build: 
      context: ./backend
      target: production
    container_name: ci-dashboard-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${BACKEND_PORT:-8001}:8001"
    volumes:
      - db_data:/app/data
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./data/dashboard.db

  frontend:
    build: 
      context: ./frontend
      target: production
    container_name: ci-dashboard-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - dashboard-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  db_data:
    driver: local

networks:
  dashboard-network:
    driver: bridge
